apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocd-autodep
  name: argocd-autodep-app
spec:
  project: argocd-autodep-project
  source:
    repoURL: https://github.com/AbdouBouallaga/argocd_dummy.git
    targetRevision: app_v1
    path: app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
