apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-autodep-project
  labels:
    app: argocd-autodep
spec:
  # Allow manifests to deploy only from Sokube git repositories 
  sourceRepos:
  - "https://github.com/AbdouBouallaga/*"
  # Only permit to deploy applications in the same cluster
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false