apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-autodep-project
  labels:
    app: argocd-autodep
spec:
  sourceRepos:
  - "https://github.com/AbdouBouallaga/*"
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false