server_name = "babdelkaS"
server_ip = "192.168.42.110"
client_name = "babdelkaSW"
client_ip = "192.168.42.111"

server_script = <<-SHELL
    sudo su
    apk add curl
    curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 sh -s - --flannel-iface=eth1
    echo "Sleeping for 5 seconds to wait for k3s to start"
    sleep 5
    sudo cat /var/lib/rancher/k3s/server/token > /home/vagrant/token
    SHELL

client_script = <<-SHELL
    sudo su
    apk add curl
    export K3S_TOKEN_FILE=/home/vagrant/token
    export K3S_URL=https://192.168.42.110:6443
    curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 sh -s - --flannel-iface=eth1
    echo "Sleeping for 5 seconds to wait for k3s to start"
    sleep 5
    SHELL


Vagrant.configure("2") do |config|

    config.vm.define server_name do |server|
        server.vm.box = "centos/8"
        server.vm.hostname = server_name
        server.vm.network :private_network, ip: server_ip
        server.vm.provider "virtualbox" do |vb|
            vb.name = server_name
            vb.gui = false
            vb.cpus = 1
            vb.customize ['modifyvm', :id, '--audio', 'none']
            vb.memory = "1024"
        end
        server.vm.provision "shell", inline: server_script
    end
    config.trigger.after :up do |trigger|
        trigger.run = {inline: "vagrant scp babdelkaS:/home/vagrant/token ./"}
    end

    config.vm.define client_name do |client|
        client.vm.box = "centos/8"
        client.vm.hostname = client_name
        client.vm.network :private_network, ip: client_ip
        client.vm.provision "file", source: "./token", destination: "/home/vagrant/token"
        client.vm.provider "virtualbox" do |vb|
            vb.name = client_name
            vb.gui = false
            vb.cpus = 1
            vb.customize ['modifyvm', :id, '--audio', 'none']
            vb.memory = "1024"
        end
        client.vm.provision "shell", inline: client_script
    end

end

