# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

server_ip = "192.168.42.110"
client1_ip = "192.168.42.111"
__server = "babdelkaS"
__client1 = "babdelkaSW"

server_script = <<-SHELL
	sudo su
    apk add curl
    curl -sfL https://get.k3s.io | sh -s - $INSTALL_K3S_EXEC --write-kubeconfig-mode 644 --disable-agent --flannel-ifa=eth1
    echo "Sleeping for 5 seconds to wait for k3s to start"
    sleep 5
    # cp /var/lib/rancher/k3s/server/token /tmp/k3sconfig/
    # cp /etc/rancher/k3s/k3s.yaml /tmp/k3sconfig/
    SHELL
	
	
# client_script = <<-SHELL
# 	sudo su
#     apk add curl
# 	K3S_KUBECONFIG_MODE="644"
# 	INSTALL_K3S_EXEC="--flannel-iface=eth1"
#     export K3S_TOKEN_FILE=/root/k3sconfig/token
#     export K3S_URL=https://#{server_ip}:6443
#     curl -sfL https://get.k3s.io | sh -
#     SHELL

Vagrant.configure("2") do |config|

    config.vm.define __server do |server|
        server.vm.box = "centos/8"
        server.vm.hostname = __server
        server.vm.network "public_network", ip: server_ip
		config.vm.provision "file", source: "./cfg", destination: "~/k3sconfig"
        server.vm.provider "virtualbox" do |vb|
            vb.name = __server
            vb.gui = false
            vb.cpus = 1
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            vb.customize ['modifyvm', :id, '--audio', 'none']
            vb.memory = "512"
        end
		server.vm.provision "shell", inline: server_script
    end

    # config.vm.define __client1 do |client|
    #     client.vm.box = "centos/8"
    #     client.vm.hostname = __client1
    #     client.vm.network "public_network", ip: client1_ip
	# 	config.vm.provision "file", source: "./cfg", destination: "~/k3sconfig"
    #     client.vm.provider "virtualbox" do |vb|
    #         vb.name = __client1
    #         vb.gui = true
    #         vb.cpus = 1
    #         vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    #         vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    #         vb.memory = "512"
    #     end
	# 	client.vm.provision "shell", inline: client_script
    # end


  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end

