script = <<-SHELL
    sudo curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 sh -s - --flannel-iface=eth1
    echo "Sleeping for 10 seconds to wait for k3s to start"
    sleep 10
    sudo cat /var/lib/rancher/k3s/server/token
    ip a show eth1 | grep "inet "
    cd /vagrant
    tar xvf archive.tar
    echo "deploying gitlab"
    /usr/local/bin/kubectl create namespace gitlab
    /usr/local/bin/kubectl apply -f /vagrant/scripts/gitlab_sc/service.yaml
    /usr/local/bin/kubectl apply -f /vagrant/scripts/gitlab_sc/glconfig.yaml
    /usr/local/bin/kubectl apply -f /vagrant/scripts/gitlab_sc/deployment.yaml
    /usr/local/bin/kubectl apply -f /vagrant/scripts/gitlab_sc/ingress.yaml
    echo "Sleeping for 10 minutes to wait for gitlab deployment"
    sleep 600
    cd /vagrant/scripts
    /usr/local/bin/kubectl create namespace argocd
    /usr/local/bin/kubectl apply -f install.yaml -n argocd
    sleep 10
    /usr/local/bin/kubectl apply -f ingress.yaml -n argocd
    echo "used https://bcrypt-generator.com/ to generate password hash"
    /usr/local/bin/kubectl -n argocd patch secret argocd-secret \
      -p '{"stringData": {
        "admin.password": "$2a$10$sKPFVu8k2JkGRo2nBVR6kOpeKDsv.SJ35qSmvXNmwkmV.avp3bWwm",
        "admin.passwordMtime": "'$(date +%FT%T%Z)'"
      }}'
    /usr/local/bin/kubectl create namespace dev
    /usr/local/bin/kubectl apply -f project.yaml -n argocd
    /usr/local/bin/kubectl apply -f application.yaml -n argocd
    echo "argocd will be ready soon"

    SHELL

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.hostname = "part3bonus"
  config.vm.provider "virtualbox" do |vb|
          vb.name = "part3bonus"
          vb.gui = false
          vb.cpus = 4
          vb.customize ['modifyvm', :id, '--audio', 'none']
          vb.memory = "5700"
  end
  config.vm.network "public_network", bridge: "en0: Ethernet", ip: "10.12.99.1", netmask: "brd 10.12.255.255", gateway: "10.12.254.254"
  # config.vm.synced_folder './gitlab', '/srv/gitlab', disabled: false
  # config.vm.provision :file, source: "./scripts", destination: "~/"
  config.vm.provision "shell", inline: script
end