apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: docker.io/etoews/hello-kubernetes:latest
        ports:
        - containerPort: 30311
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  labels:
    app: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: app-two
        image: docker.io/etoews/hello-kubernetes:latest
        ports:
        - containerPort: 30312
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
  labels:
    app: app-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
      - name: app-three
        image: docker.io/etoews/hello-kubernetes:latest
        ports:
        - containerPort: 30313
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  ports:
  - name: http
    port: 80
    targetPort: 30311
  selector:
    app: app-one
---
apiVersion: v1
kind: Service
metadata:
  name: app-two
  labels:
    app: app-two
spec:
  ports:
  - name: http
    port: 80
    targetPort: 30312
  selector:
    app: app-two
---
apiVersion: v1
kind: Service
metadata:
  name: app-three
  labels:
    app: app-three
spec:
  ports:
  - name: http
    port: 80
    targetPort: 30313
  selector:
    app: app-three