apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: gitlab
data:
  gitlab.rb: |-
    gitlab_rails['gitlab_shell_ssh_port'] = 32222
    prometheus['monitor_kubernetes'] = false
    gitlab_rails['initial_root_password'] = "toortoor"
    external_url 'http://gitlab.10.12.99.1.nip.io'
    nginx['listen_port'] = 80
    nginx['listen_https'] = false
    registry_external_url 'http://reg.gitlab.10.12.99.1.nip.io'
    gitlab_rails['registry_enabled'] = true
    registry_nginx['listen_port'] = 5050
    registry_nginx['listen_https'] = false