script = <<-SHELL
    sudo ./scripts/script.sh
    SHELL

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "part3bonus"
  config.vm.network :private_network, ip: "192.168.100.100"
  config.vm.provision :file, source: "./scripts", destination: "~/"
  config.vm.provider "virtualbox" do |vb|
          vb.name = "part3bonus"
          vb.gui = false
          vb.cpus = 2
          vb.customize ['modifyvm', :id, '--audio', 'none']
          vb.memory = "2048"
  end
  config.vm.provision "shell", inline: script
end