script = <<-SHELL
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
    systemctl restart sshd.service
    sudo curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 sh -s - --flannel-iface=eth1
    echo "Sleeping for 10 seconds to wait for k3s to start"
    sleep 10
    ip a show eth1 | grep "inet "
    cd /vagrant/scripts
    /usr/local/bin/kubectl create namespace argocd
    /usr/local/bin/kubectl apply -f install.yaml -n argocd
    sleep 10
    /usr/local/bin/kubectl apply -f ingress.yaml -n argocd
    echo "used https://bcrypt-generator.com/ to generate password hash"
    /usr/local/bin/kubectl -n argocd patch secret argocd-secret \
    -p '{"stringData": {
      "admin.password": "$2a$10$sKPFVu8k2JkGRo2nBVR6kOpeKDsv.SJ35qSmvXNmwkmV.avp3bWwm",
      "admin.passwordMtime": "'$(date +%FT%T%Z)'"
      }}'
      /usr/local/bin/kubectl create namespace dev
      /usr/local/bin/kubectl apply -f project.yaml -n argocd
      /usr/local/bin/kubectl apply -f application.yaml -n argocd
      echo "argocd will be ready soon, 10s the token will be displayed"
      sleep 10
      sudo cat /var/lib/rancher/k3s/server/token > /vagrant/token
      cat /vagrant/token
      echo "past this token into https://pastebin.com/ to share with your team"
      sleep 30
      /usr/local/bin/kubectl taint nodes part3bonus key1=value1:NoSchedule
    SHELL

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.hostname = "part3bonus"
  config.vm.provider "virtualbox" do |vb|
          vb.name = "part3bonus"
          vb.gui = false
          vb.cpus = 4
          vb.customize ['modifyvm', :id, '--audio', 'none']
          vb.memory = "2548"
  end
  config.vm.network "public_network", bridge: "en0: Ethernet", ip: "10.12.99.255", netmask: "brd 10.12.255.255", gateway: "10.12.254.254"
  # config.vm.synced_folder './gitlab', '/srv/gitlab', disabled: false
  # config.vm.provision :file, source: "./scripts", destination: "~/"
  config.vm.provision "shell", inline: script
end