server_script = <<-SHELL
    sudo curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 sh -s - --flannel-iface=eth1
    echo "Sleeping for 10 seconds to wait for k3s to start"
    sleep 10
    sudo cat /var/lib/rancher/k3s/server/token
    ip a show eth1 | grep "inet "
    SHELL

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.hostname = "BabdelkaMaster"
  config.vm.network "public_network", bridge: "en0: Ethernet", ip: "10.12.99.1", netmask: "brd 10.12.255.255", gateway: "10.12.254.254"
  config.vm.provider "virtualbox" do |vb|
          vb.name = "BabdelkaMaster"
          vb.gui = false
          vb.cpus = 2
          vb.customize ['modifyvm', :id, '--audio', 'none']
          vb.memory = "1500"
  end
  config.vm.provision "shell", inline: server_script
end